[SECRET]
# Code à 4 chiffres pour accéder à l'interface web (ex: 1234)
web_pin = 1234

[DEVICES]
# Liste des smartphones autorisés (Nom = Identifiant_iPhone)
# Exemple : dev_0 = Mon_Smartphone
dev_0 = VOTRE_NOM_TELEPHONE

[CAMERA]
# Nom qui apparaîtra dans les alertes (ex: Caméra_Salon)
name = JanusEye_Cam
# Rotation : 0, 90, 180 ou 270 (selon la position du Pi)
rotation = 180
# Résolution conseillée : 640x480
size = 640x480
# Sensibilité détection (plus le chiffre est petit, plus c'est sensible)
sensitivity = 5000
# Luminosité (0 par défaut, ajuster si l'image est trop sombre)
brightness = 0

[FREE_SMS]
# Identifiants fournis par Free Mobile (Option Notifications par SMS)
user_id = VOTRE_ID_FREE_SMS
api_key = VOTRE_CLE_API_FREE 

[EMAIL]
# Configuration pour l'envoi des photos par mail
smtp_server = smtp.gmail.com
smtp_port = 587
sender_email = VOTRE_EMAIL_EXPEDITEUR@gmail.com
# Utiliser un "Mot de passe d'application" Google (16 caractères)
sender_password = VOTRE_MOT_DE_PASSE_APPLICATION
receiver_email = EMAIL_QUI_RECOIT_LES_ALERTES@gmail.com

[NTFY]
# Nom du Topic unique pour l'application NTFY (ex: januseye_votre_nom_aleatoire)
topic = VOTRE_TOPIC_UNIQUE_ICI

[EVENTS]
# Activez (true) ou Désactivez (false) les alertes par service
sms_motion = false
sms_toggle = false
sms_on_block = false
mail_motion = true
mail_toggle = true
mail_security = true
# Alertes via l'application NTFY
ntfy_motion = false
ntfy_toggle = false
ntfy_on_block = false

[STORAGE]
# Nombre de jours avant suppression automatique des images
retention_days = 30
